# Generated by Django 3.2 on 2023-03-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth0UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth0_role', models.CharField(max_length=32, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='auth0_user_roles', to='auth.Group')),
            ],
            options={
                'ordering': ('auth0_role',),
            },
        ),
    ]
