# Generated by Django 3.2 on 2023-04-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth0_sso', '0002_auth0userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth0userrole',
            name='auth0_role_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='auth0userrole',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
